# Site settings
title: kymjs张涛
email: kymjs123@gmail.com
description: 张涛的博客
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

github_username:  kymjs
duoshuo_username: kymjs
permalink: /:categories/:year/:month/:day/:title 

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

paginate: 10
paginate_path: "page:num"

links:
  - title: 关于
    url: /about/
  - title: 友链
    url: /link/
  - title: 捐赠
    url: /donate/
